package com.jgz.gateway.mapper;

import com.jgz.gateway.model.Filter;
import com.jgz.gateway.model.FilterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int countByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insert(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insertSelective(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    List<Filter> selectByExample(FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    Filter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Filter record, @Param("example") FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExample(@Param("record") Filter record, @Param("example") FilterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKeySelective(Filter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filter
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKey(Filter record);
}