package com.jgz.gateway.mapper;

import com.jgz.gateway.model.Predicate;
import com.jgz.gateway.model.PredicateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PredicateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int countByExample(PredicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByExample(PredicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insert(Predicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insertSelective(Predicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    List<Predicate> selectByExample(PredicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    Predicate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Predicate record, @Param("example") PredicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExample(@Param("record") Predicate record, @Param("example") PredicateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKeySelective(Predicate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table predicate
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKey(Predicate record);
}