server:
  port: 8899

spring:
  redis:
    database: 0
    host: 192.168.1.14
    port: 6379
    password: redis
    timeout: 2000ms
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 256
        max-idle: 8
        min-idle: 1
        max-wait: -1ms
