package com.jgz.gateway.manage.model;

public class Filter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.name
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filter.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.id
     *
     * @return the value of filter.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.id
     *
     * @param id the value for filter.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.route_id
     *
     * @return the value of filter.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.route_id
     *
     * @param routeId the value for filter.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.name
     *
     * @return the value of filter.name
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.name
     *
     * @param name the value for filter.name
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column filter.value
     *
     * @return the value of filter.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column filter.value
     *
     * @param value the value for filter.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}