package com.jgz.gateway.manage.model;

public class Predicate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predicate.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predicate.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer routeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predicate.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String ukey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column predicate.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predicate.id
     *
     * @return the value of predicate.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predicate.id
     *
     * @param id the value for predicate.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predicate.route_id
     *
     * @return the value of predicate.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predicate.route_id
     *
     * @param routeId the value for predicate.route_id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predicate.ukey
     *
     * @return the value of predicate.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getUkey() {
        return ukey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predicate.ukey
     *
     * @param ukey the value for predicate.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setUkey(String ukey) {
        this.ukey = ukey == null ? null : ukey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column predicate.value
     *
     * @return the value of predicate.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column predicate.value
     *
     * @param value the value for predicate.value
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}