package com.jgz.gateway.manage.model;

public class Route {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String ukey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.uri
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private String uri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.ord
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Integer ord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.state
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    private Boolean state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.id
     *
     * @return the value of route.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.id
     *
     * @param id the value for route.id
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.ukey
     *
     * @return the value of route.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getUkey() {
        return ukey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.ukey
     *
     * @param ukey the value for route.ukey
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setUkey(String ukey) {
        this.ukey = ukey == null ? null : ukey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.uri
     *
     * @return the value of route.uri
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public String getUri() {
        return uri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.uri
     *
     * @param uri the value for route.uri
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setUri(String uri) {
        this.uri = uri == null ? null : uri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.ord
     *
     * @return the value of route.ord
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Integer getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.ord
     *
     * @param ord the value for route.ord
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setOrd(Integer ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.state
     *
     * @return the value of route.state
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.state
     *
     * @param state the value for route.state
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    public void setState(Boolean state) {
        this.state = state;
    }
}