package com.jgz.gateway.manage.mapper;

import com.jgz.gateway.manage.model.Route;
import com.jgz.gateway.manage.model.RouteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RouteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int countByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insert(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int insertSelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    List<Route> selectByExample(RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    Route selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExampleSelective(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByExample(@Param("record") Route record, @Param("example") RouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKeySelective(Route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table route
     *
     * @mbggenerated Tue May 03 19:14:59 CST 2022
     */
    int updateByPrimaryKey(Route record);
}